"use strict";

module.exports = {
  ROLES: ["HSE_ADMIN", "HSE_REVIEWER", "USER"],
  USER_STATUS: ["ACTIVE", "INACTIVE"],
  REPORT_TYPES: ["UNSAFE_ACT", "UNSAFE_CONDITION", "NEAR_MISS"],
  REPORT_STATUS: ["NEW", "ANALYZED", "UNDER_REVIEW", "CLOSED"],
  PRIORITIES: ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
  ANALYSIS_STATUS: ["PENDING", "COMPLETED", "FAILED"],
  GENERIC_STATUS: ["ACTIVE", "INACTIVE"],
};
