"""Prototype rule registry.

PROTOTYPE ONLY — "Prototype output for system integration testing; not a
production safety prediction model." These keyword rules are NOT official OIL
methodology and prototype confidence is NOT an injury probability.

Rule codes live in a PROTO-* namespace so they can never be mistaken for
official Life-Saving Rule codes. Node resolves them against its own table
and stores NULL when there is no match.
"""

RULES = [
    {
        "code": "PROTO-ENERGY-ISOLATION",
        "activity": "Maintenance",
        "hazard": "Uncontrolled Energy",
        "barrierFailure": "Energy Isolation",
        "consequence": "Electrocution",
        "lifeSavingRuleCode": "PROTO-ENERGY-ISOLATION",
        "priority": "HIGH",
        "confidence": 0.82,
        "phrases": [
            "without isolating",
            "without isolation",
            "isolating the electrical supply",
            "isolation",
            "lockout",
            "lock out",
            "tag out",
            "tagout",
            "de-energize",
            "deenergize",
            "live wire",
            "live cable",
            "electrical supply",
        ],
    },
    {
        "code": "PROTO-WORK-AT-HEIGHT",
        "activity": "Work at Height",
        "hazard": "Fall from Height",
        "barrierFailure": "Fall Protection",
        "consequence": "Fall Injury",
        "lifeSavingRuleCode": "PROTO-WORK-AT-HEIGHT",
        "priority": "HIGH",
        "confidence": 0.78,
        "phrases": [
            "working at height",
            "work at height",
            "without harness",
            "no harness",
            "scaffold",
            "unprotected edge",
            "open edge",
            "ladder",
        ],
    },
    {
        "code": "PROTO-CONFINED-SPACE",
        "activity": "Confined Space Entry",
        "hazard": "Hazardous Atmosphere",
        "barrierFailure": "Confined Space Permit",
        "consequence": "Asphyxiation",
        "lifeSavingRuleCode": "PROTO-CONFINED-SPACE",
        "priority": "CRITICAL",
        "confidence": 0.85,
        "phrases": [
            "confined space",
            "without gas test",
            "no gas test",
            "manhole",
            "vessel entry",
            "tank entry",
        ],
    },
    {
        "code": "PROTO-LIFTING",
        "activity": "Lifting Operations",
        "hazard": "Suspended Load",
        "barrierFailure": "Exclusion Zone",
        "consequence": "Struck By Load",
        "lifeSavingRuleCode": "PROTO-LIFTING",
        "priority": "HIGH",
        "confidence": 0.75,
        "phrases": [
            "suspended load",
            "under the load",
            "crane",
            "lifting",
            "rigging",
            "standing under",
        ],
    },
    {
        "code": "PROTO-LINE-BREAKING",
        "activity": "Line Breaking",
        "hazard": "Pressurized Release",
        "barrierFailure": "Line Break Permit",
        "consequence": "Chemical Exposure",
        "lifeSavingRuleCode": "PROTO-LINE-BREAKING",
        "priority": "HIGH",
        "confidence": 0.74,
        "phrases": [
            "line break",
            "breaking the line",
            "flange",
            "pressurized",
            "under pressure",
            "drain valve",
        ],
    },
    {
        "code": "PROTO-VEHICLE",
        "activity": "Vehicle Movement",
        "hazard": "Moving Vehicle",
        "barrierFailure": "Traffic Control",
        "consequence": "Vehicle Collision",
        "lifeSavingRuleCode": "PROTO-VEHICLE",
        "priority": "MEDIUM",
        "confidence": 0.62,
        "phrases": [
            "reversing vehicle",
            "vehicle reversing",
            "forklift",
            "no spotter",
            "without spotter",
            "speeding",
        ],
    },
    {
        "code": "PROTO-BYPASSED-BARRIER",
        "activity": None,
        "hazard": "Bypassed Safeguard",
        "barrierFailure": "Safety Interlock",
        "consequence": "Uncontrolled Operation",
        "lifeSavingRuleCode": "PROTO-BYPASSED-BARRIER",
        "priority": "MEDIUM",
        "confidence": 0.6,
        "phrases": [
            "bypassed",
            "bypass",
            "interlock defeated",
            "guard removed",
            "safety device disabled",
        ],
    },
]
